### ISSUE TITLE
Error in script: 'Seq' object has no attribute 'alphabet'

### ISSUE THREAD

**Issue by chan-98** [swarris/pyPaSWAS#11]
I ran this command after installing Biopython.
Since the pypaswas.py was not executable, this is the command I ran:

python3 pyPaSWAS/pypaswas.py SO_11372_E13_NPC_UT_6_hr_070922_R1.fastq SO_11372_E13_NPC_UT_6_hr_070922_R2.fastq -1 fastq -2 fastq

Error:

Traceback (most recent call last):
  File "/home/ctprouser/aligner_tool/pyPaSWAS/pypaswas.py", line 11, in <module>
    ppw.run()
  File "/home/ctprouser/aligner_tool/pyPaSWAS/pyPaSWAS/pypaswasall.py", line 207, in run
    query_sequences = self._get_query_sequences(self.arguments[0], start=query_start, end=query_end)
  File "/home/ctprouser/aligner_tool/pyPaSWAS/pyPaSWAS/pypaswasall.py", line 104, in _get_query_sequences
    reader.read_records(start,end)
  File "/home/ctprouser/aligner_tool/pyPaSWAS/pyPaSWAS/Core/Readers.py", line 105, in read_records
    self.records = [SWSeqRecord(Seq(str(record.seq), record.seq.alphabet),
  File "/home/ctprouser/aligner_tool/pyPaSWAS/pyPaSWAS/Core/Readers.py", line 105, in <listcomp>
    self.records = [SWSeqRecord(Seq(str(record.seq), record.seq.alphabet),
AttributeError: 'Seq' object has no attribute 'alphabet'

I am not much of a programmer. Please debug and tell me what needs to be done to fix it?

**Comment by nik875** [comment]
Should be fixed after the latest commit to master branch.

**Comment by swarris** [comment]
Indeed, should be fixed now
